version: '3.9'

networks:
  dev:

x-base-api: &base-project
  volumes:
    - ./:/opt/app
  build:
    context: .
    dockerfile: Dockerfile

services:
  project:
    <<: *base-project
    command: ["gunicorn", "Redone.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8001:8000"
    networks:
      - dev 