# Generated by Django 4.2 on 2025-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_product_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="price1",
        ),
        migrations.AddField(
            model_name="product",
            name="price2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size1",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="size2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
