# Generated by Django 4.2 on 2025-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_about_product_about_ru_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="category",
            new_name="category_ru",
        ),
        migrations.AddField(
            model_name="categories",
            name="category_uz",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
