# Generated by Django 4.2 on 2025-04-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_category_categories_category_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Top_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200)),
                ("name_ru", models.CharField(max_length=200)),
                ("size1", models.CharField(max_length=10)),
                ("price1", models.IntegerField()),
                ("size2", models.CharField(blank=True, max_length=10, null=True)),
                ("price2", models.IntegerField(blank=True, null=True)),
                ("about_uz", models.TextField(blank=True, null=True)),
                ("about_ru", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="images")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.categories"
                    ),
                ),
            ],
        ),
    ]
