# Generated by Django 4.2 on 2025-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_product_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
